### ISSUE TITLE
Unable to send Mailbox Msg

### ISSUE THREAD

**Issue by Jodsderechte** [oscarpedrero/BloodyMailBox#1]
Getting an Internal error when trying to send a Mailbox msg. 

LogOutput.log
```
[Warning:VampireCommandFramework] Hit unexpected exception executing command send
: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at BloodyMailBox.Utils.MailBox.ReadMailBox(String user)
   at BloodyMailBox.Utils.MailBox.MessageToMailBox(String user, String message, String fromUser)
   at BloodyMailBox.Server.Commands.MailBoxCommands.SendMail(ChatCommandContext ctx, String name, String message)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at VampireCommandFramework.CommandRegistry.Handle(ICommandContext ctx, String input)
[Info   :KindredCommands] Jods had an internal error trying to use command: .mailbox send DerMarokkaner Test
```

**Comment by oscarpedrero** [comment]
What chat command do you use?

**Comment by Jodsderechte** [comment]
.mailbox send DerMarokkaner Test (and that is the correct name of the other player)

**Comment by oscarpedrero** [comment]
The command would be `.mailbox send DerMarokkaner "Test (and that is the correct name of the other player)"`

**Comment by Jodsderechte** [comment]
sadly "" doesn't seem to do the trick either

`
[Warning:VampireCommandFramework] Hit unexpected exception executing command send
: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at BloodyMailBox.Utils.MailBox.ReadMailBox(String user)
   at BloodyMailBox.Utils.MailBox.MessageToMailBox(String user, String message, String fromUser)
   at BloodyMailBox.Server.Commands.MailBoxCommands.SendMail(ChatCommandContext ctx, String name, String message)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at VampireCommandFramework.CommandRegistry.Handle(ICommandContext ctx, String input)
[Info   :KindredCommands] Jods had an internal error trying to use command: .mailbox send DerMarokkaner "Test!"`


Command: .mailbox send DerMarokkaner "Test!"
